version: '3.8'

services:
  db-test:
    image: postgres:latest
    restart: always
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_test

  cache-test:
    image: redis:latest
    container_name: redis-test-db
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
