services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  default:
    name: memolingo_network
