"""Remove unique for word, category

Revision ID: 001ea35a4120
Revises: 
Create Date: 2025-05-26 15:39:29.099021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001ea35a4120'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_title_key', 'category', type_='unique')
    op.drop_column('category', 'translation')
    op.drop_constraint('word_wrd_key', 'word', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('word_wrd_key', 'word', ['wrd'])
    op.add_column('category', sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('category_title_key', 'category', ['title'])
    # ### end Alembic commands ###
