"""Expand User model

Revision ID: aaba24e7a0f8
Revises: 32bc7a8f88a2
Create Date: 2025-04-28 22:56:17.497826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aaba24e7a0f8"
down_revision: Union[str, None] = "32bc7a8f88a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_access_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("name", sa.String(length=64), nullable=True))
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.drop_column("user", "name")
    op.drop_column("user", "google_access_token")
    # ### end Alembic commands ###
