"""Change password column

Revision ID: 32bc7a8f88a2
Revises: 597f57a4bddd
Create Date: 2025-04-09 15:47:59.422219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32bc7a8f88a2"
down_revision: Union[str, None] = "597f57a4bddd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###
