"""Create api_v1 tables

Revision ID: 597f57a4bddd
Revises:
Create Date: 2025-04-09 13:42:33.116967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "597f57a4bddd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("description", sa.String(), server_default="", nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(), server_default="", nullable=True),
        sa.Column("email", sa.String(), server_default="", nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "word",
        sa.Column("wrd", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("transcription", sa.String(), server_default="", nullable=True),
        sa.Column("description", sa.String(), server_default="", nullable=True),
        sa.Column("img", sa.String(), server_default="", nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wrd"),
    )
    op.create_table(
        "category_word_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "word_id", name="category_word"),
    )
    op.create_table(
        "userword",
        sa.Column(
            "status",
            sa.Enum("new", "known", "revise", "end", name="status"),
            nullable=False,
        ),
        sa.Column(
            "t_stamp", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["word.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "word_id", name="user_word"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userword")
    op.drop_table("category_word_association")
    op.drop_table("word")
    op.drop_table("user")
    op.drop_table("category")
    # ### end Alembic commands ###
