"""Create UserProgress table

Revision ID: b61e5de12598
Revises: 02f67b5851ee
Create Date: 2025-03-04 14:31:36.346707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b61e5de12598"
down_revision: Union[str, None] = "02f67b5851ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprogress",
        sa.Column(
            "status",
            sa.Enum("NotStudy", "OnStudy", "EndStudy", name="status"),
            nullable=False,
        ),
        sa.Column(
            "t_stamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("category", sa.Column("description", sa.String(), nullable=True))
    op.add_column("user", sa.Column("password", sa.String(), nullable=True))
    op.add_column("user", sa.Column("email", sa.String(), nullable=True))
    op.add_column("word", sa.Column("transcription", sa.String(), nullable=True))
    op.add_column("word", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("word", "description")
    op.drop_column("word", "transcription")
    op.drop_column("user", "email")
    op.drop_column("user", "password")
    op.drop_column("category", "description")
    op.drop_table("userprogress")
    # ### end Alembic commands ###
