"""Edit User model: add join_date

Revision ID: 3ea2185fd443
Revises: fdf45f4fc93c
Create Date: 2025-06-14 10:16:57.376016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea2185fd443'
down_revision: Union[str, None] = 'fdf45f4fc93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###
